# Linear Algebra Assignment

**Instructions:**
- Read each question carefully before answering.
- For **written/conceptual** questions, double-click the answer cell below the question and type your response.
- For **coding** questions, write your solution in the code cell provided.
- Run all code cells before submitting — make sure there are no errors.
- When done, click **"Save in GitHub to keep changes"** at the top to submit.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [1]:
# Run this cell before starting — do not modify
import numpy as np

---
## Q2 — Matrix Transformations

You are given the following matrix:

$$A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$$

And the following vectors:

```
v1 = [1, 0]
v2 = [0, 1]
v3 = [1, 1]
v4 = [-2, 4]
```

### Q2 Part (i) — Geometric Interpretation

**Without running any code**, predict what happens when you multiply matrix `A` by each of the vectors above.
Explain **geometrically** what the matrix is doing to each vector — not just what the numbers become.

a*v1 = 2x1 matrix 2,0. geometrically,vector lies in x axis with stretched 2 times its original size

a*v2 = 2x1 matrix with 0,3. geometrically, vector remains perfectly on y axis with matris scaling the y direction by 3 so vector is streatched 3 times.

a*v3 = 2x1 matrix with 2,3. vector points diagonallyy with horizontal stretch by 2 and vertical stretch by 3. the vector's angle changes and it gets steeper and tilt more towards y axis.

a*v4 = 2x1 matrix with -4, 12. geometrically, x component doubled and y component is triples. vector in upper left quandrant stretched and steeper angle towards y axis

### Q2 Part (ii) — Respond to a Classmate

A classmate says:
> *"Matrix multiplication is just a complicated way to multiply numbers — it doesn't mean anything visually."*

Using your results from Part (i), write **3–4 sentences** proving them wrong.

AS seen by the geometric interpretation of matrix multiplication, it is a mathematical tool to stretch, squash and rotate geometric space like a rubber sheath. thus its not just a simple muliplication, it is the foundation for how computer graphics scale, skew and animate object on your screen.

### Q2 Part (iii) — NumPy Function

Write a NumPy function that:
- Takes **any 2×2 matrix** and **any 2D vector** as inputs
- Returns the **transformed vector**
- Prints a **one-line description** of how the x and y components individually change

Test your function on matrix `A` and all four vectors above.

In [2]:
# Input — do not modify
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])


In [6]:
def transform_and_describe(matrix, vector):
    """
    Multiplies a 2x2 matrix by a 2D vector, prints a description of
    the component changes, and returns the new vector.
    """
    # Perform matrix multiplication using the @ operator (or np.dot)
    transformed = matrix @ vector

    # Print a one-line description of how x and y individually changed
    print(f"x changed from {vector[0]} to {transformed[0]}, and y changed from {vector[1]} to {transformed[1]}")

    return transformed

vectors = {'v1': v1, 'v2': v2, 'v3': v3, 'v4': v4}

# Test the function on matrix A and all four vectors
for name, v in vectors.items():
    print(f"Testing {name}:")
    new_v = transform_and_describe(A, v)
    print(f"Result: {new_v}\n")

Testing v1:
x changed from 1 to 2, and y changed from 0 to 0
Result: [2 0]

Testing v2:
x changed from 0 to 0, and y changed from 1 to 3
Result: [0 3]

Testing v3:
x changed from 1 to 2, and y changed from 1 to 3
Result: [2 3]

Testing v4:
x changed from -2 to -4, and y changed from 4 to 12
Result: [-4 12]



---
## Q3 — Tiny Recommendation System

Each user's taste is represented as a vector of 4 scores across 4 genres — **action, romance, thriller, comedy** — all between 0 and 1.

```
User A: [0.9, 0.1, 0.8, 0.2]
User B: [0.1, 0.9, 0.2, 0.8]
User C: [0.8, 0.2, 0.9, 0.1]
User D: [0.5, 0.5, 0.5, 0.5]
```

### Q3 Part (i) — Similarity Matrix

Compute the **full similarity matrix** — every user's similarity score against every other user — using only a **single NumPy operation** (no loops).

What linear algebra concept makes this possible in one line?

In [14]:
# Input — do not modify
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])


In [8]:
# Write your code here:
similarity_matrix = users @ users.T
similarity_matrix

array([[1.5 , 0.5 , 1.48, 1.  ],
       [0.5 , 1.5 , 0.52, 1.  ],
       [1.48, 0.52, 1.5 , 1.  ],
       [1.  , 1.  , 1.  , 1.  ]])

**What linear algebra concept makes this possible in one line?**


The concept that makes this possible in one line is Matrix Multiplication, specifically multiplying a matrix by its Transpose. Multiplying a user matrix by its transpose simultaneously calculates the dot product between every pair of rows, instantly cross-referencing everyone's taste alignment in a single operation.

### Q3 Part (ii) — Reason About User D

User D has **equal scores** across all genres.

Before computing anything, reason through: will User D's similarity score with every other user be identical? **Why or why not?** Then verify with code.

Yes, User D's similarity score with Users A, B, and C will be exactly identical.Because all three users have the exact same total sum (2.0), their dot product with User D will all be identical: 0.5 X 2.0 = 1.0.

In [11]:
# Write your code here:

# Define the user vectors
user_a = np.array([0.9, 0.1, 0.8, 0.2])
user_b = np.array([0.1, 0.9, 0.2, 0.8])
user_c = np.array([0.8, 0.2, 0.9, 0.1])
user_d = np.array([0.5, 0.5, 0.5, 0.5])

# Calculate D's dot product with A, B, and C
sim_d_a = np.dot(user_d, user_a)
sim_d_b = np.dot(user_d, user_b)
sim_d_c = np.dot(user_d, user_c)

print(f"User D & A Similarity: {sim_d_a}")
print(f"User D & B Similarity: {sim_d_b}")
print(f"User D & C Similarity: {sim_d_c}")

User D & A Similarity: 1.0
User D & B Similarity: 1.0
User D & C Similarity: 1.0


### Q3 Part (iii) — The Problem with Raw Dot Products

A senior engineer tells you:
> *"Raw dot products are a bad measure of similarity — you need to normalize."\*

1. What is the **problem** with raw dot products?
2. Construct a **specific example using NumPy** that demonstrates the flaw.
3. Fix it.

> **Hint:** Take a user with scores `[1.8, 0.2, 1.6, 0.4]`

The fundamental flaw with the raw dot product is that it measures two things at the same time: alignment (how similar the tastes are) and magnitude (how big the numbers are).
Because the math is just multiplying and adding, a user who simply rates everything highly (or watches way more movies) will generate massive dot products.

In [13]:
# Write your code here:

#2. Demonstrating the Flaw with NumPy
user_a = np.array([0.9, 0.1, 0.8, 0.2])
# The Hint: Exact same taste ratios, but double the magnitude
user_e = np.array([1.8, 0.2, 1.6, 0.4])

# The Loud Mismatch: Different taste, but huge numbers
user_loud = np.array([3.0, 3.0, 0.0, 0.0])

print(f"A's similarity to themselves: {np.dot(user_a, user_a):.2f}")
print(f"A's similarity to User E:     {np.dot(user_a, user_e):.2f}")
print(f"A's similarity to User Loud:  {np.dot(user_a, user_loud):.2f}")

#3. The Fix: Cosine Similarity (Normalization)

def cosine_similarity(v1, v2):
    # Divide the dot product by the product of both magnitudes
    dot_product = np.dot(v1, v2)
    mag1 = np.linalg.norm(v1)
    mag2 = np.linalg.norm(v2)
    return dot_product / (mag1 * mag2)

print(f"Fixed A & A:    {cosine_similarity(user_a, user_a):.2f}")
print(f"Fixed A & E:    {cosine_similarity(user_a, user_e):.2f}")
print(f"Fixed A & Loud: {cosine_similarity(user_a, user_loud):.2f}")

A's similarity to themselves: 1.50
A's similarity to User E:     3.00
A's similarity to User Loud:  3.00
Fixed A & A:    1.00
Fixed A & E:    1.00
Fixed A & Loud: 0.58


### Q3 Part (iv) — Most Similar Users

After normalizing, which **two users are most similar**?

Does that match your intuition from just reading the vectors?

What does it mean in plain language — what do these two users have in common?

> **Note:** A similarity score is just a number that tells you **how alike two things are**.

User  A and C most similar with cosine similarity score of 0.99(out of perfect 1.0).

It matches with intuition as If you look at the pattern, both users rate the first and third genres (Action and Thriller) extremely high, while giving very low scores to the second and fourth genres (Romance and Comedy). Their numbers are just slightly swapped around, but the overall "shape" of their taste is almost identical.

In plain English, a high cosine similarity score means these two people are going to enjoy the exact same movie recommendations.Even though User A might like Action slightly more than Thrillers, and User C likes Thrillers slightly more than Action, they both aggressively prefer intense, high-stakes movies over lighthearted or romantic ones.

In [15]:
# Write your code here:
user_names = ['A', 'B', 'C', 'D']
magnitudes = np.linalg.norm(users, axis=1, keepdims=True)
normalized_users = users / magnitudes
cosine_sim_matrix = normalized_users @ normalized_users.T

print("--- Full Cosine Similarity Matrix ---")
print(np.round(cosine_sim_matrix, 2))
print("\n")

search_matrix = cosine_sim_matrix.copy()
np.fill_diagonal(search_matrix, -1) # Ignore self-matches

# Locate the highest score
flat_index = np.argmax(search_matrix)
row_idx, col_idx = np.unravel_index(flat_index, search_matrix.shape)

user_1 = user_names[row_idx]
user_2 = user_names[col_idx]
max_score = search_matrix[row_idx, col_idx]

print("--- Most Similar Pair ---")
print(f"Users {user_1} and {user_2} with a score of {max_score:.4f}")

--- Full Cosine Similarity Matrix ---
[[1.   0.33 0.99 0.82]
 [0.33 1.   0.35 0.82]
 [0.99 0.35 1.   0.82]
 [0.82 0.82 0.82 1.  ]]


--- Most Similar Pair ---
Users A and C with a score of 0.9867


---

## 🎉 Submission Complete!

Make sure all code cells are run and all written answers are filled in, then click **"Save in GitHub to keep changes"** at the top.